### ISSUE TITLE
Serialize into a JavaScript object?

### ISSUE THREAD

**Issue by zaiste** [eno-lang/enolib#4]
Is it possible to serialize an Eno file directly into a JavaScript object (or I missed something) ?

**Comment by simonrepp** [comment]
First of all no worries, you did not miss anything :) There is a `.raw()` method (*) you can call on the document (or any other element) to serialize it into a native JS object - this is intended for inspecting and debugging though:

```js
enolib.parse('> note\ngreeting: hello').raw();
// returns approximately [ { comment: 'note', key: 'greeting', value: 'hello' } ]
```

Background: Given that the eno language itself has no knowledge of types there would be no way to serialize a value to anything other than `string`, and given that eno documents and elements can flexibly represent both associative and sequential data structures, there would also be no canonical serialization structure that would be an optimal data layout for both usecases (`.raw()` needs to return a sequential representation because a pure associative representation would lose the order).

So indeed one has to manually serialize the document! The reward for this is implicit validation, all the types one can imagine and a lot less syntax and overhead when writing content, but yes it takes some getting used to. :)

Any further questions, just let me know - thanks for having a look!

(*) I'll make sure to add it to the documentation (which is still fresh), got overlooked sorry :) And I'll also see that I create an FAQ entry on the general topic of serialization on the website, I think this would be very helpful as I realize now.

**Comment by simonrepp** [comment]
One more thing: I'm considering some of the feedback and questions I received lately - would you feel that for instance an included CLI tool to infer and auto-generate boilerplate deserialization code would be something helpful for your particular way of working? Or would you rather just write the serialization code from scratch yourself and would prefer, e.g. better documentation, or more examples, or something else instead? Thanks for your feedback in advance :)

**Comment by simonrepp** [comment]
Update: I added the missing documentation for `raw()` and an FAQ entry on this topic at https://eno-lang.org/enolib/javascript/addendum/faq/ :tada:
